import { useRouter } from "next/router";
import { NextIntlProvider } from "next-intl";
import { Fragment } from "react";
import th from "../messages/th.json";
import mm from "../messages/mm.json";
import ls from "../messages/ls.json";
import cd from "../messages/cd.json";
import Head from "next/head";
import NavBar from "../components/NavBar";
import "../styles/globals.css";
import { CssBaseline } from "@mui/material";
import Footer from "../components/Footer";
import store from "../redux/store";
import { Provider } from "react-redux";

const messages = {
  th,
  mm,
  ls,
  cd,
};

function MyApp({ Component, pageProps }) {
  const { locale, pathname } = useRouter();

  function checkPage() {
    if (pathname === "/auth") return false;
    return true;
  }

  return (
    <Fragment>
      <Head>
        <title>Aorsortor - Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextIntlProvider locale={locale} messages={messages[locale]}>
        <CssBaseline></CssBaseline>
        <Provider store={store}>
          {checkPage() ? (
            <Fragment>
              <NavBar locale={locale}></NavBar>
              <Component {...pageProps} />
              <Footer></Footer>
            </Fragment>
          ) : (
            <Component {...pageProps} />
          )}
        </Provider>
      </NextIntlProvider>
    </Fragment>
  );
}

export default MyApp;
